# orders/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'orders'

# Router for ViewSet (recommended approach)
router = DefaultRouter()
router.register('orders', views.OrderViewSet, basename='order')

urlpatterns = [
    # ==========================================================================
    # Option 1: Function-based views (for learning)
    # ==========================================================================
    # path('orders/', views.order_list, name='order-list'),
    # path('orders/<int:pk>/', views.order_detail, name='order-detail'),

    # ==========================================================================
    # Option 2: ViewSet with Router (recommended)
    # This automatically creates all the URLs above + custom actions!
    # ==========================================================================
    path('', include(router.urls)),
]

# =============================================================================
# URLs generated by the router:
#
# /api/orders/              GET (list), POST (create)
# /api/orders/{id}/         GET (detail), PUT, PATCH, DELETE
# /api/orders/pending/      GET (custom action - list pending orders)
# /api/orders/{id}/confirm/ POST (custom action - confirm order)
# =============================================================================
