"""Decision guide — which collection for which job."""


print("=" * 60)
print("  WHICH COLLECTION SHOULD I USE?")
print("=" * 60)
print()
print("  PROBLEM                          → COLLECTION")
print("  ─────────────────────────────────────────────────")
print("  Group items by key               → defaultdict(list)")
print("  Count occurrences                → Counter")
print("  Fast append/pop from both ends   → deque")
print("  Sliding window / last N items    → deque(maxlen=N)")
print("  BFS queue                        → deque (popleft)")
print("  Immutable record with names      → NamedTuple")
print("  Layered config / scopes          → ChainMap")
print("  Set as dict key / in a set       → frozenset")
print("  Order-sensitive equality          → OrderedDict")
print("  LRU cache                        → OrderedDict")
print("  Custom dict (uppercase keys)     → UserDict subclass")
print("  Validated list (positive only)   → UserList subclass")
print("  Case-insensitive string          → UserString subclass")
print("  Thread-safe queue                → queue.Queue")
print("  ─────────────────────────────────────────────────")
print()
print("  PERFORMANCE CHEATSHEET:")
print("  ─────────────────────────────────────────────────")
print("  Operation          list       deque")
print("  append right       O(1)       O(1)")
print("  append left        O(n)!      O(1)  ← deque wins")
print("  pop right          O(1)       O(1)")
print("  pop left           O(n)!      O(1)  ← deque wins")
print("  random access      O(1)       O(n)  ← list wins")
print("  ─────────────────────────────────────────────────")
print()
print("  MUTABILITY CHEATSHEET:")
print("  ─────────────────────────────────────────────────")
print("  Mutable            Immutable (frozen)")
print("  list               tuple")
print("  set                frozenset")
print("  dict               MappingProxyType")
print("  bytearray          bytes")
print("  deque              —")
print("  ─────────────────────────────────────────────────")
