# Generated by Django 6.0.3 on 2026-03-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration for multi-table inheritance.

    This creates separate tables for Food and Beverage that link back
    to MenuItem via a OneToOneField (menuitem_ptr).

    Database tables created:
    - menu_food (menuitem_ptr_id, is_vegetarian, calories)
    - menu_beverage (menuitem_ptr_id, is_alcoholic, volume_ml)
    """

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('menuitem_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='menu.menuitem'
                )),
                ('is_alcoholic', models.BooleanField(default=False)),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Beverage Item',
                'verbose_name_plural': 'Beverage Items',
            },
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('menuitem_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='menu.menuitem'
                )),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
            },
            bases=('menu.menuitem',),
        ),
    ]
