# Generated by Django 6.0.3 on 2026-03-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_food_beverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='menuitem_ptr',
        ),
        migrations.DeleteModel(
            name='Beverage',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
