# Generated by Django 6.0.3 on 2026-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_beverage_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for display (e.g., #ff0000)', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menu.tag'),
        ),
    ]
