# Generated by Django 6.0.3 on 2026-03-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_food_menuitem_ptr_delete_beverage_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('is_alcoholic', models.BooleanField(default=False)),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('menu.menuitem',),
        ),
    ]
